import "/styles/globals.css";
import React from "react";
import Nav from "../../components/Nav";
import Provider from "../../components/Provider";
import { StateContext } from "../../context/StateContext";
import { Toaster } from "react-hot-toast";


export const metadata = {
  title: "Arto",
  description: "Generated by create next app",
};

const RootLayout = ({children, session}) => {
  return (
    <html lang='en'>
      <body>
        <Provider session={session}>
        <StateContext>
        <main>
          <Toaster />
          <div className="background-container relative z-10 overflow-hidden">
            <Nav className='z-10'/>
            <div className="main z-[-2]">
              <div className="z-0 relative">
              {children}
              </div>
              <div className="glow-effect absolute inset-0 z-[-1]"/>
            </div>
            
          </div>
          
        </main>
        </StateContext>
      </Provider>
      </body>
    </html>
  )
}

export default RootLayout
